export const FETCH_CHARACTERS = 'MyList/FETCH_CHARACTERS';
export const FETCH_CHARACTERS_SUCCESS = 'MyList/FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_FAILURE = 'MyList/FETCH_CHARACTERS_FAILURE';
